/* File: pairwise_fortmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct  7 11:54:25 2014
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pairwise_fort_error;
static PyObject *pairwise_fort_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(pairwise_fort_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = pairwise_fort_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(pairwise_fort,PAIRWISE_FORT)(double*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* pairwise_fort *******************************/
static char doc_f2py_rout_pairwise_fort_pairwise_fort[] = "\
D = pairwise_fort(X,[m,n])\n\nWrapper for ``pairwise_fort``.\
\n\nParameters\n----------\n"
"X : input rank-2 array('d') with bounds (m,n)\n"
"\nOther Parameters\n----------------\n"
"m : input int, optional\n    Default: shape(X,0)\n"
"n : input int, optional\n    Default: shape(X,1)\n"
"\nReturns\n-------\n"
"D : rank-2 array('d') with bounds (m,m)";
/* extern void F_FUNC_US(pairwise_fort,PAIRWISE_FORT)(double*,double*,int*,int*); */
static PyObject *f2py_rout_pairwise_fort_pairwise_fort(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *X = NULL;
  npy_intp X_Dims[2] = {-1, -1};
  const int X_Rank = 2;
  PyArrayObject *capi_X_tmp = NULL;
  int capi_X_intent = 0;
  PyObject *X_capi = Py_None;
  double *D = NULL;
  npy_intp D_Dims[2] = {-1, -1};
  const int D_Rank = 2;
  PyArrayObject *capi_D_tmp = NULL;
  int capi_D_intent = 0;
  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"X","m","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|OO:pairwise_fort.pairwise_fort",\
    capi_kwlist,&X_capi,&m_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable X */
  ;
  capi_X_intent |= F2PY_INTENT_IN;
  capi_X_tmp = array_from_pyobj(NPY_DOUBLE,X_Dims,X_Rank,capi_X_intent,X_capi);
  if (capi_X_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pairwise_fort_error,"failed in converting 1st argument `X' of pairwise_fort.pairwise_fort to C/Fortran array" );
  } else {
    X = (double *)(capi_X_tmp->data);

  /* Processing variable m */
  if (m_capi == Py_None) m = shape(X,0); else
    f2py_success = int_from_pyobj(&m,m_capi,"pairwise_fort.pairwise_fort() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(X,0)==m,"shape(X,0)==m","1st keyword m","pairwise_fort:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(X,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"pairwise_fort.pairwise_fort() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(X,1)==n,"shape(X,1)==n","2nd keyword n","pairwise_fort:n=%d",n) {
  /* Processing variable D */
  D_Dims[0]=m,D_Dims[1]=m;
  capi_D_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_D_tmp = array_from_pyobj(NPY_DOUBLE,D_Dims,D_Rank,capi_D_intent,Py_None);
  if (capi_D_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pairwise_fort_error,"failed in converting hidden `D' of pairwise_fort.pairwise_fort to C/Fortran array" );
  } else {
    D = (double *)(capi_D_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(X,D,&m,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_D_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_D_tmp == NULL) ... else of D*/
  /* End of cleaning variable D */
  } /*CHECKSCALAR(shape(X,1)==n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(shape(X,0)==m)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  if((PyObject *)capi_X_tmp!=X_capi) {
    Py_XDECREF(capi_X_tmp); }
  }  /*if (capi_X_tmp == NULL) ... else of X*/
  /* End of cleaning variable X */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pairwise_fort ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"pairwise_fort",-1,{{-1}},0,(char *)F_FUNC_US(pairwise_fort,PAIRWISE_FORT),(f2py_init_func)f2py_rout_pairwise_fort_pairwise_fort,doc_f2py_rout_pairwise_fort_pairwise_fort},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "pairwise_fort",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_pairwise_fort(void) {
#else
#define RETVAL
PyMODINIT_FUNC initpairwise_fort(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = pairwise_fort_module = PyModule_Create(&moduledef);
#else
  m = pairwise_fort_module = Py_InitModule("pairwise_fort", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module pairwise_fort (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'pairwise_fort' is auto-generated with f2py (version:2).\nFunctions:\n"
"  D = pairwise_fort(X,m=shape(X,0),n=shape(X,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  pairwise_fort_error = PyErr_NewException ("pairwise_fort.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"pairwise_fort");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
